"use client";
import { Menu, PenLine, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { ModeToggle } from "./ModeToggle";
import { authClient } from "@/lib/auth-client";

const links = [{ label: "Home", href: "/" }, { label: "Stories", href: "/blogs" }, { label: "About", href: "/about" }];
export function Navbar() { const [open, setOpen] = useState(false); const { data: session } = authClient.useSession(); return <header className="sticky top-0 z-50 border-b bg-background/90 backdrop-blur-xl"><nav className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5"><Link href="/" className="text-xl font-black tracking-tight">INKLINE<span className="text-amber-500">.</span></Link><div className="hidden items-center gap-8 md:flex">{links.map((link) => <Link key={link.href} href={link.href} className="text-sm font-semibold text-muted-foreground transition hover:text-foreground">{link.label}</Link>)}</div><div className="hidden items-center gap-2 md:flex"><ModeToggle />{session ? <><Link href="/dashboard" className="rounded-full border px-4 py-2 text-sm font-semibold">Dashboard</Link><button onClick={() => authClient.signOut()} className="rounded-full bg-foreground px-4 py-2 text-sm font-semibold text-background">Sign out</button></> : <><Link href="/login" className="px-3 py-2 text-sm font-semibold">Sign in</Link><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-foreground px-4 py-2 text-sm font-bold text-background"><PenLine className="size-4" />Start writing</Link></>}</div><button className="md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></nav>{open && <div className="border-t px-5 py-5 md:hidden"><div className="flex flex-col gap-4">{links.map((link) => <Link onClick={() => setOpen(false)} key={link.href} href={link.href} className="font-semibold">{link.label}</Link>)}<Link href={session ? "/dashboard" : "/login"} className="rounded-xl bg-foreground p-3 text-center font-bold text-background">{session ? "Dashboard" : "Sign in"}</Link></div></div>}</header>; }
